cors:
  originPatterns: http://localhost:4200,http://localhost:8082,http:192.168.25.202:8082,http://192.168.25.202:4200
signature:
  path: "C:/savemed/resources/upload/"
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB
  datasource:
    url: jdbc:sqlserver://SRVM2B;databaseName=SAVE_038;encrypt=false;
    username: sa
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: SQL_SERVER
    show-sql: false
    hibernate:
      nam
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
springdoc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
server:
  port: 8082